# Site settings
title: "BIOINF 525"
email: bjgrant@umich.edu
description: > # this means to ignore newlines until "baseurl:"
   Winter 2016 course at the University of Michigan introducing  
   computational tools, techniques and best practices that foster 
   reproducible research in bioinformatics, genome informatics 
   and biostatistics.
baseurl: "/bioinf525_w16" # the subpath of your site, e.g. /blog/
url: "http://bioboot.github.io/bioinf525_w16" 
twitter_username: bioboot
github_username:  bioboot

# Build settings
markdown: kramdown
